name: CI Android

on:
  push:
    branches: [main]
    paths:
      - 'android/**'

  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'android/**'

jobs:
  build_android:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: android

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11.0.3
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11.0.3

      - name: Kotlin Linter
        uses: vroy/gha-kotlin-linter@v3

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Library with Gradle and check lints
        run: ./gradlew build test

      - name: Unit tests results
        uses: actions/upload-artifact@v2
        with:
          name: play-unit-tests-results
          path: build/reports/tests/testPlayDebugUnitTest/index.html
