name: CI Example App Android

on:
  push:
    branches: [main]
    paths:
      - 'example/android/**'

  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'example/android/**'

jobs:
  build_android_example:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: example/android

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Setup kernel for react native, increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - name: Set up JDK 11.0.3
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11.0.3

      - name: Grant execute permission for gradlew in example app
        run: chmod +x ./gradlew

      - name: Build with example app with Gradle
        run: ./gradlew build test
